### ISSUE TITLE
ovirt-guest-agent role doesn't work on 3.6

### ISSUE THREAD

**Issue by lukas-bednar** [rhevm-qe-automation/ovirt-ansible#134]
yaml config:
```yaml
---
ovirt_guest_agent_pkg_prefix: rhevm
ovirt_rpm_repo: http://somewhere/builds/3.6/rhv-3.6.12-1/rhv-release-3.6.12-1-001.noarch.rpm
```
error
```
ERROR! The requested handler 'enable and start rhevm-guest-agent' was not found in either the main handlers list nor in the listening handlers list
```
