### ISSUE TITLE
Project layout

### ISSUE THREAD

**Issue by xrow** [rhevm-qe-automation/ovirt-ansible#79]
Hi,

I was planning to reuse our roles. Unfortunatelly I can`t since the roles are not in their own repository. As an improvement I would recommend having the playbook in one repo and the roles in other repos.

If want to reuse your work, I need to copy your roles . This is not ideal. 

Thanks for your efforts.

**Comment by lukas-bednar** [comment]
Do you suggest to split and put each role into separate repository?

I don't have problem to reuse this module across projects.
Consider such playbook organization:
```
my-playbook/
  requirements.yml
  config.yml
  inventory
```
where  requirements.yml looks like:
```yaml
---
- src: bennojoy.ntp
  name: ntp
- src: https://github.com/rhevm-qe-automation/ovirt-ansible.git
  version: 0.0.3
  name: ovirt-deployment
```
and config.yml looks like:
```yaml
---
- hosts: all
  roles:
    -
      role: 'ntp'
      ntp_server:
        - 'europe.pool.ntp.org'
    - role: "ovirt-deployment/roles/ovirt-common"

- hosts: engine
  roles:
    - role: "ovirt-deployment/roles/ovirt-engine-install-packages"
    - role: "ovirt-deployment/roles/ovirt-engine-setup"
```
then you can execute that like this:
```sh
# create dir for 3rd party (depending/required) roles
cd my-playbook
mkdir -p roles
# install required roles
ansible-galaxy install -r requirements.yml   -p roles/
# run ansible playbook
ansible-playbook -i inventory config.yml
```

Please let me know if you have problem with that.
